{% set name = "lenskit" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c67ca8257e1362746bcf48110034d6361f5b258452d314005a694ad30448807

build:
  number: 0
  noarch: python
  script: |
    {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python >=3.7.0
    - pip
    - flit-core
  run:
    - python >=3.7.0
    - pandas >=0.24
    - numpy >=1.17
    - scipy >=1.2
    - numba >=0.51,<0.55
    - pyarrow >=0.15
    - cffi >=1.12.2
    - psutil >=5
    - binpickle >=0.3.2
    - seedbank >=0.1.0
    - csr >=0.3.1
  run_constrained:
    - tensorflow >=2.1
    - scikit-learn >=0.22

test:
  imports:
    - lenskit
    - lenskit.algorithms.als

about:
  home: https://lenskit.org
  doc_url: https://lkpy.lenskit.org/
  dev_url: https://github.com/lenskit/lkpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

extra:
  recipe-maintainers:
    - mdekstrand
