{% set name = "lenskit" %}
{% set version = "2025.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a46dedbe43683aeb40a52fd97ed6fb3b9b06cc3dd62aa3e7be974d90d37d8b02

build:
  number: 0
  noarch: python
  script: |
    {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - pandas >=1.0
    - numpy >=1.19
    - scipy >=1.2
    - numba >=0.51,<0.60
    - cffi >=1.12.2
    - psutil >=5
    - binpickle >=0.3.2
    - seedbank >=0.1.0
    - csr >=0.3.1
  run_constrained:
    - scikit-learn >=0.22

test:
  requires:
    - python {{ python_min }}
  imports:
    - lenskit
    - lenskit.algorithms.als

about:
  home: https://lenskit.org
  doc_url: https://lkpy.lenskit.org/
  dev_url: https://github.com/lenskit/lkpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

extra:
  recipe-maintainers:
    - mdekstrand
