{% set name = "lenskit" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 862b17a028eea4e37d0f193deab93bcf4314fdb47b96ea3b8bf4e010d652d656

build:
  number: 0
  noarch: python
  script: |
    # build helper library for Conda/MKL
    {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python >=3.6.1
    - pip
    - flit-core
  run:
    - python >=3.6.1
    - pandas >=0.24
    - numpy >=1.16
    - scipy >=1.2
    - csr =0.2
    - numba >=0.51,<0.53
    - pyarrow >=0.15
    - binpickle >=0.3.2
  run_constrained:
    - tensorflow >=2.1
    - scikit-learn >=0.22

test:
  imports:
    - lenskit
    - lenskit.algorithms.als

about:
  home: https://lenskit.org
  doc_url: https://lkpy.lenskit.org/
  dev_url: https://github.com/lenskit/lkpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

extra:
  recipe-maintainers:
    - mdekstrand
