{% set name = "lenskit" %}
{% set version = "2025.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a46dedbe43683aeb40a52fd97ed6fb3b9b06cc3dd62aa3e7be974d90d37d8b02

build:
  number: 0
  noarch: python
  script: |
    {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling =1
    - hatch-vcs =0.4
  run:
    - python >={{ python_min }}
    - typing-extensions >=4.12,<5
    - pyarrow >=15
    - pandas >=2.0,<3
    - numpy >=1.25,<3
    - scipy >=1.11,<2
    - pytorch >=2.4,<3
    - more-itertools >=9.0
    - threadpoolctl >=3.0
    - structlog >=23.2
    - rich >=13.5,<14
    - pyzmq >=24
    - click >=8.1,<9
    - pydantic >=2.7,<3
    - humanize >=4.2,<5
    - prettytable >=3.14,<4

test:
  requires:
    - python {{ python_min }}
  imports:
    - lenskit
    - lenskit.data
    - lenskit.als
    - lenskit.knn

{# outputs:
  - name: lenskit
    version: {{ version }}
  - name: lenskit-funksvd
    version: {{ version }}
    requirements:
      run:
        - lenskit {{ version }}
        - numba >=0.56
  - name: lenskit-sklearn
    version: {{ version }}
    requirements:
      run:
        - lenskit {{ version }}
        - scikit-learn >=1.2,<2
  - name: lenskit-implicit
    version: {{ version }}
    requirements:
      run:
        - lenskit {{ version }}
        - implicit >=0.7.2
  - name: lenskit-hpf
    version: {{ version }}
    requirements:
      run:
        - lenskit {{ version }}
        - hpfrec =0.2 #}

about:
  home: https://lenskit.org
  doc_url: https://lkpy.lenskit.org/
  dev_url: https://github.com/lenskit/lkpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

extra:
  recipe-maintainers:
    - mdekstrand
