{% set name = "lenskit" %}
{% set version = "0.14.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a90f85d164d04e48cd41f32c0225f8150142ae3f4d2f5da8403f573731efe9d

build:
  number: 1
  noarch: python
  script: |
    {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python >=3.8.0,<3.12
    - pip
    - flit-core
  run:
    - python >=3.7.0
    - pandas >=1.0
    - numpy >=1.19
    - scipy >=1.2
    - numba >=0.51,<0.60
    - cffi >=1.12.2
    - psutil >=5
    - binpickle >=0.3.2
    - seedbank >=0.1.0
    - csr >=0.3.1
  run_constrained:
    - scikit-learn >=0.22

test:
  imports:
    - lenskit
    - lenskit.algorithms.als

about:
  home: https://lenskit.org
  doc_url: https://lkpy.lenskit.org/
  dev_url: https://github.com/lenskit/lkpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Recommender systems tools for Python
  description: |
    LensKit is an open-source toolkit for building, researching, and learning
    about recommender systems.

extra:
  recipe-maintainers:
    - mdekstrand
